export const PASSWORD_RECOVERY_INIT = "PASSWORD_RECOVERY_INIT";

export const PASSWORD_RECOVERY = "PASSWORD_RECOVERY";
export const PASSWORD_RECOVERY_OK = "PASSWORD_RECOVERY_OK";
export const PASSWORD_RECOVERY_ERROR = "PASSWORD_RECOVERY_ERROR";
