export const CHANGE_PASSWORD_INIT = "CHANGE_PASSWORD_INIT";

export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_OK = "CHANGE_PASSWORD_OK";
export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR";
